const typeWeapons = [
  {
    id: 1,
    name: "Ak47",
    img: "https://i.imgur.com/o9SMMTP.png",
    pecas: "150",
    metal: "8",
    gatilho: "1",
    molas: "5",
  },
  {
    id: 2,
    name: "Five Seven",
    img: "https://i.imgur.com/LH9zn1L.png",
    pecas: "30",
    metal: "2",
    gatilho: "1",
    molas: "0",
  },
  {
    id: 3,
    name: "Tec-9",
    img: "https://i.imgur.com/RI0eJz2.png",
    pecas: "50",
    metal: "2",
    gatilho: "1",
    molas: "2",
  },
  {
    id: 4,
    name: "Thompsom",
    img: "https://i.imgur.com/dgAVeey.png",
    pecas: "100",
    metal: "6",
    gatilho: "1",
    molas: "3",
  },
  {
    id: 5,
    name: "Hk",
    img: "https://www.seekpng.com/png/full/263-2638818_c1vu3za-gta-san-andreas-pistol-icon.png",
    pecas: "20",
    metal: "1",
    gatilho: "1",
    molas: "0",
  },
  {
    id: 6,
    name: "MTar",
    img: "https://i.imgur.com/o9SMMTP.png",
    pecas: "100",
    metal: "6",
    gatilho: "1",
    molas: "3",
  },
];

export default typeWeapons;
